#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

#cleanCase
cd CFD
rm -rf processor*
rm  log.*
rm  ../DEM/post/liggghts*
rm -r constant/polyMesh
cd ..
#------------------------------------------------------------------------------
